### ISSUE TITLE
StanHeaders missing lang directory (rstan does not install)

### ISSUE THREAD

**Issue by chendaniely** [stan-dev/rstan#175]
Installing Stan 2.7 breaks.

Using Arch Linux.  Seems like StanHeaders is not installing properly so when rstan tries to compile the missing headers are missing.  I downloaded the tar file from cran and installed StanHeaders via `install.packages` and StanHeaders still seems to have missing files...

StanHeaders dir:

```
[dchen@archie-t440s stan]$ pwd
/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include/stan
[dchen@archie-t440s stan]$ ls
math  math.hpp

```

Install output:

```
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c chains.cpp -o chains.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c init.cpp -o init.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__ast_def.cpp -o lang__ast_def.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__bare_type_grammar_inst.cpp -o lang__grammars__bare_type_grammar_inst.o

*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***

lang__grammars__bare_type_grammar_inst.cpp:18:57: fatal error: stan/lang/grammars/bare_type_grammar_inst.cpp: No such file or directory
compilation terminated.
/usr/lib64/R/etc/Makeconf:143: recipe for target 'lang__grammars__bare_type_grammar_inst.o' failed
make: *** [lang__grammars__bare_type_grammar_inst.o] Error 1
make: *** Waiting for unfinished jobs....
lang__ast_def.cpp:18:33: fatal error: stan/lang/ast_def.cpp: No such file or directory
compilation terminated.
/usr/lib64/R/etc/Makeconf:143: recipe for target 'lang__ast_def.o' failed
make: *** [lang__ast_def.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/rstan’

The downloaded source packages are in
    ‘/tmp/Rtmp3v1IDA/downloaded_packages’
Warning message:
In install.packages("rstan", repos = "http://cran.rstudio.com",  :
  installation of package ‘rstan’ had non-zero exit status

```

**Comment by syclik** [comment]
I watched over Daniel's shoulder. It only has the math subdirectory after a
new install of StanHeaders.

**Comment by chendaniely** [comment]
in the `tar.gz` file under `StanHeaders/inst/include/stan` the only thing is the math subdirectory.
There's a bunch of other header files under `StanHeaders/inst/include/src/stan`  so it seems like a path was set incorrectly?

**Comment by chendaniely** [comment]
confirmed.  after I copied all the files from `src/stan` to `/stan` so it looks like this:

```
[dchen@archie-t440s stan]$ pwd
/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include/stan
[dchen@archie-t440s stan]$ ls
command  interface  io  lang  math  math.hpp  mcmc  model  msinttypes.h  optimization  services  variational  version.hpp
```

it worked

**Comment by chendaniely** [comment]
my (successful) install log

```
> install.packages("rstan", repos = "http://cran.rstudio.com")
Installing package into ‘/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/rstan_2.7.0-1.tar.gz'
Content type 'application/x-gzip' length 1093296 bytes (1.0 MB)
==================================================
downloaded 1.0 MB


*** Successfully loaded .Rprofile ***


Welcome at Tue Jul 21 16:50:08 2015 
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c chains.cpp -o chains.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c init.cpp -o init.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__ast_def.cpp -o lang__ast_def.o
g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__bare_type_grammar_inst.cpp -o lang__grammars__bare_type_grammar_inst.o

*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***


*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__expression07_grammar_inst.cpp -o lang__grammars__expression07_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__expression_grammar_inst.cpp -o lang__grammars__expression_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__functions_grammar_inst.cpp -o lang__grammars__functions_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__program_grammar_inst.cpp -o lang__grammars__program_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__statement_2_grammar_inst.cpp -o lang__grammars__statement_2_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__statement_grammar_inst.cpp -o lang__grammars__statement_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__term_grammar_inst.cpp -o lang__grammars__term_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__var_deccls_grammar_inst.cpp -o lang__grammars__var_deccls_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c lang__grammars__whitespace_grammar_inst.cpp -o lang__grammars__whitespace_grammar_inst.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c misc.cpp -o misc.o

*** Successfully loaded .Rprofile ***

g++ -I/usr/include/R/ -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -D_FORTIFY_SOURCE=2 -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/RcppEigen/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/StanHeaders/include"   -fpic  -O3 -flto -ffat-lto-objects -c stanc.cpp -o stanc.o

*** Successfully loaded .Rprofile ***

g++ -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro -o rstan.so chains.o init.o lang__ast_def.o lang__grammars__bare_type_grammar_inst.o lang__grammars__expression07_grammar_inst.o lang__grammars__expression_grammar_inst.o lang__grammars__functions_grammar_inst.o lang__grammars__program_grammar_inst.o lang__grammars__statement_2_grammar_inst.o lang__grammars__statement_grammar_inst.o lang__grammars__term_grammar_inst.o lang__grammars__var_deccls_grammar_inst.o lang__grammars__whitespace_grammar_inst.o misc.o stanc.o -L/usr/lib64/R/lib -lR
installing to /home/dchen/R/x86_64-unknown-linux-gnu-library/3.2/rstan/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded

*** Successfully loaded .Rprofile ***


Welcome at Tue Jul 21 16:52:55 2015 

Goodbye at  Tue Jul 21 16:52:56 2015 
* DONE (rstan)

Goodbye at  Tue Jul 21 16:52:56 2015 

The downloaded source packages are in
    ‘/tmp/Rtmp3v1IDA/downloaded_packages’
> library(rstan)
Loading required package: Rcpp
Loading required package: inline

Attaching package: ‘inline’

The following object is masked from ‘package:Rcpp’:

    registerPlugin

hrstan (Version 2.7.0-1, packaged: 2015-07-17 18:12:01 UTC, GitRev: 05c3d0058b6a)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
> help(rstan)

```

**Comment by bgoodri** [comment]
How was the StanHeaders R package installed?

**Comment by syclik** [comment]
install.packages.

If you look at Daniel's output, the include paths that should be derived
through Rscript are not evaluating and it's just including the command to
find the path.

**Comment by maverickg** [comment]
It's not folder `lang` is not there.  It is under `src`:

```
$ ls /Library/Frameworks/R.framework/Resources/library/StanHeaders/include/src/stan/
command      interface    io           lang         mcmc         model        optimization services     variational  version.hpp
```

The problem here for him is the following did not get what is supposed to get

```
-I"`"/usr/lib64/R/bin/Rscript" -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`"
```

because of output in .Rprofile.  We forgot to put the vanilla thing in calling Rscript here.

**Comment by bgoodri** [comment]
I'll put `--vanilla`

**Comment by syclik** [comment]
Thanks!

**Comment by chendaniely** [comment]
fixed in 18cb605ff7a53894270e9c51ba8436d2711ec87b

**Comment by jorgesinval** [comment]
I copied the files from the folder inside the tar.gz folder, to the `StanHeaders/include/stan` folder, and I still get an error:

```
/usr/lib/R/etc/Makeconf:168: recipe for target 'lang__grammars__expression_grammar_inst.o' failed
make: *** [lang__grammars__expression_grammar_inst.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/home/sinval/R/x86_64-pc-linux-gnu-library/3.4/rstan’
* restoring previous ‘/home/sinval/R/x86_64-pc-linux-gnu-library/3.4/rstan’
Warning in install.packages :
  installation of package ‘rstan’ had non-zero exit status
```

**Comment by bgoodri** [comment]
This issue was fixed over two years ago. If you are having an installation problem, please open a new issue with the full error message.

**Comment by jorgesinval** [comment]
Thanks, I did it.
