### ISSUE TITLE
Unknown variable: to_vector

### ISSUE THREAD

**Issue by MOOnLyer** [stan-dev/rstan#576]
#### Summary:
When I try to compile the Stan model, it gives some warning.
DIAGNOSTIC(S) FROM PARSER:
Unknown variable: to_vector
Unknown variable: to_vector

#### Reproducible Steps:
glmm.stan :
data {
  int<lower=1> num_clust;
  int<lower=1> num_obs;
  int<lower=1> num_pred;
  int<lower=1> num_basis;
  int<lower=1> num_time;

  matrix[num_obs,num_basis] Z;
  int<lower=0,upper=1> Y[num_obs];
  int<lower=1,upper=num_clust> id[num_obs];
  matrix[num_obs,num_pred] X;
  int<lower=1> times[num_obs];

  // Stuff for computing generated quants
  int<lower=1> num_test;
  int<lower=1> num_test_clust;
  matrix[num_test,num_basis] Z_test;
  int<lower=0,upper=1> Y_test[num_test];
  matrix[num_test,num_pred] X_test;
  int<lower=1,upper=num_test_clust> id_test[num_test];
  int<lower=1> times_test[num_test];

}

parameters {
  vector[num_time] alpha;
  vector[num_pred] beta;
  matrix[num_basis, num_clust] z_b;
  matrix[num_basis, num_test_clust] z_b_test;

  cholesky_factor_corr[num_basis] Omega_b;
  vector<lower=0, upper=pi()/2>[num_basis] tau_unif;
}

transformed parameters {
  vector<lower=0>[num_basis] tau;
  matrix[num_clust, num_basis] b;
  matrix[num_test_clust, num_basis] b_test;

  for(k in 1:num_basis) tau[k] = 2.5 * tan(tau_unif[k]);
  b = (diag_pre_multiply(tau, Omega_b) * z_b)';
  b_test = (diag_pre_multiply(tau, Omega_b) * z_b_test)';

}

model {
  vector[num_obs] eta;
  real tmp;

  eta = X * beta;

  alpha               ~ cauchy(0,5);
  to_vector(z_b)      ~ normal(0,1);
  to_vector(z_b_test) ~ normal(0,1);
  beta                ~ cauchy(0,2.5);
  Omega_b             ~ lkj_corr_cholesky(2);
  
  for(i in 1:num_obs) {
    tmp = dot_product(Z[i,1:num_basis], b[id[i], 1:num_basis]);
    Y[i] ~ bernoulli_logit(alpha[times[i]] + tmp + eta[i]);
  }

}

generated quantities {
  vector[num_test_clust] loglik_test;
  vector[num_test] eta_test;
  real tmp2;
  real p;

  eta_test = X_test * beta;
  for(i in 1:num_test_clust) loglik_test[i] = 0.;

  for(i in 1:num_test) {
    tmp2 = dot_product(Z_test[i,1:num_basis], b_test[id_test[i], 1:num_basis]);
    /* loglik_test[id_test[i]] += inv_logit(alpha[times_test[i]] + tmp2 + eta_test[i]); */
    p = inv_logit(alpha[times_test[i]] + tmp2 + eta_test[i]);
    loglik_test[id_test[i]] += Y_test[i] * log(p) + (1 - Y_test[i]) * log(1 - p);
  }
}

stan_model("glmm.stan")

#### Current Output:
DIAGNOSTIC(S) FROM PARSER:
Unknown variable: to_vector
Unknown variable: to_vector

#### RStan Version:
‘2.18.1’

#### R Version:
"R version 3.5.1 (2018-07-02)"

#### Operating System:
Ubuntu 18.04.1

**Comment by bgoodri** [comment]
This is a known upstream issue, but not one that affects the generated C++ code or the results.

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/stan/pull/2614

**Comment by bob-carpenter** [comment]
This is still broken on the `develop` branch of `stan-dev/stan`, which is where this issue needs to be moved.

**Comment by bob-carpenter** [comment]
Sorry---I  was confusing this with the semicolon in function arguments issue, which is also outstanding.

**Comment by lionel68** [comment]
Is this issue closed?

I have been running in the same error when trying to run the model defined in: https://mc-stan.org/docs/2_19/stan-users-guide/multivariate-hierarchical-priors-section.html

The error seems to be in this line: "to_vector(gamma) ~ normal(0, 5);"

I am using R v3.5 and rstan v2.18.

Full error report:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Unknown variable: to_vector

PARSER EXPECTED: <expression>
Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'normal_hier' due to the above error.

**Comment by mitzimorris** [comment]
just checked -  able to compile both glmm.stan from this issue, and the stan program in the user's guide - working from develop for cmdstan, i.e., 2.19 release.

**Comment by lionel68** [comment]
Thanks for your super fast reply, I indeed have other part of my model that are creating errors, but I got confused by the parser warning.
