### ISSUE TITLE
Compilation Error On While Setting up and Test Stan

### ISSUE THREAD

**Issue by stevenamcalpine** [stan-dev/rstan#637]
#### Summary:
After installing rtools and checking the contents of Markvars (empty), receiving errors while attempting to run 8schools.stan

#### Reproducible Steps:
Followed guidance and ensured rtools was installed and findable, but still getting errors while executing the first test
```
Restarting R session...

> remove.packages("rstan")
Removing package from ‘C:/Users/Steven/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘rstan’
> if (file.exists(".RData")) file.remove(".RData")
> 
> install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
Installing package into ‘C:/Users/Steven/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.5/rstan_2.18.2.zip'
Content type 'application/zip' length 4448581 bytes (4.2 MB)
downloaded 4.2 MB

package ‘rstan’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Steven\AppData\Local\Temp\4\RtmpWWDRpK\downloaded_packages
> 
> pkgbuild::has_build_tools(debug = TRUE)
[1] TRUE
> library(devtools)
Warning messages:
1: package ‘devtools’ was built under R version 3.5.3 
2: package ‘usethis’ was built under R version 3.5.3 
> find_rtools()
[1] TRUE
> has_devel()
> file.edit("~/.R/Makevars")
> 
> library("rstan") # observe startup messages
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.18.2, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
For improved execution time, we recommend calling
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
although this causes Stan to throw an error on a few processors.
Warning messages:
1: package ‘rstan’ was built under R version 3.5.3 
2: package ‘ggplot2’ was built under R version 3.5.3 
3: package ‘StanHeaders’ was built under R version 3.5.3 
> options(mc.cores = parallel::detectCores())
> rstan_options(auto_write = TRUE)
> Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
> 
> schools_dat <- list(J = 8, 
+                     y = c(28,  8, -3,  7, -1,  1, 18, 12),
+                     sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
> 
> fit <- stan(file = 'D:/R-D/Projects/2019/propval_v2/stancastle/stancastle/8schools.stan', data = schools_dat)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/Users/Steven/Documents/R/win-library/3.5/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from C:/Users/Steven/Documents/R/win-library/3.5/BH/include/boost/random/detail/int_float_pair.hpp:26,
                 from C:/Users/Steven/Documents/R/win-library/3.5/BH/include/boost/random/exponential_distribution.hpp:27,
                 from C:/Users/Steven/Documents/R/win-library/3.5/BH/include/boost/random/gamma_distribution.hpp:25,
                 from C:/Users/Steven/Documents/R/win-library/3.5/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
                 from C:/Users/Steven/Documents/R/win-library/3.5/StanHeaders/include/stan/math/prim/mat.hpp:276,
                 from C:/Users/Steven/Documents/R/win-library/3.5/StanHeaders/include/stan/math/rev/mat.hpp:12,
                 from C:/Users/Steven/Documents/R/win-library/3.5/StanHeaders/include/stan/math.hpp
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-35~1.0/bin/x64/R CMD SHLIB filea39c5bdd64e.cpp 2> filea39c5bdd64e.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

#### Current Output:
Error above
#### Expected Output:
execution of the 8schools.stan model

#### RStan Version:
2.18.2

#### R Version:
R version 3.5.0 (2018-04-23)

#### Operating System:
Windows Server 2016

**Comment by sherloconan** [comment]
Same for me on macOS Mojave (10.14.1), RStudio (1.2.1335), R (3.6.0, 2019-04-26), RStan (2.18.2).

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from file1e713a09a511.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/i
In addition: Warning messages:
1: In readLines(file, warn = TRUE) :
  incomplete final line found on '/Users/sherloconan/Documents/HU/ANLY 505-90-O/505 R/Untitled.stan'
2: In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file1e713a09a511.cpp 2> file1e713a09a511.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection


**EDIT
Managed to solve the issue by https://github.com/rmacoslib/r-macos-rtools/issues/11.**

**Comment by ode33** [comment]
This has been resolved: https://github.com/stan-dev/rstan/issues/633

Recommend closing the issue.

**Comment by RobertMyles** [comment]
@ode33 the solution in #633 seems to be for WIndows -- any tips for OSX? I've tried the dev version of rstan, but still getting this error on install:

```
   /bin/sh: XX: command not found
   make: *** [chains.o] Error 127
   ERROR: compilation failed for package ‘rstan’
─  removing ‘/private/var/folders/b9/zhbx6vgj4z1gyr8nvgfwq8djd7y1gm/T/RtmpFA3e3x/Rinst78995ed8845c/rstan’
         -----------------------------------
   ERROR: package installation failed
```

The original error (while attempting to run a stan program) is: 

```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! /bin/sh: XX: command not found
make: *** [file77f41a95274a.o] Error 127
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file77f41a95274a.cpp 2> file77f41a95274a.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

Doesn't seem to be solved yet.

*update*: [this](https://discourse.mc-stan.org/t/dealing-with-mojave/6519) thread helped me. Specifically, deleting the content on ~/.R/Makevars.

**Comment by ode33** [comment]
What's working for me is from the terminal I run 

`$ R CMD INSTALL rstan_2.18.2.tar.gz`

under

`$ clang -v`
`LLVM version 10.0.0 (clang-1000.10.44.4)`
`Target: x86_64-apple-darwin17.7.0`
`InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by janhannig** [comment]
I did not have luck with the ~/.R/Makevars and the compile error persisted. 
Eventually I removed all R and then reinstalled everything. More importantly I have relinked the command line tools using

sudo xcode-select -s  /Library/Developer/CommandLineTools

It relinked the command line tools to the newest version.

**Comment by stevenamcalpine** [comment]
Problem solved for windows by changing the Markvars.win file to 
`CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native`
and ensuring there are no returns in the line

**Comment by yifeiFaye** [comment]
I was having same compiling issue. I solved it following these steps:
1) install the xcode CommandLineTools. it was not previously installed after I upgrade os to mojave. 
sudo installer -pkg \
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg \
-target /

2)find Makevars file and empty it. then run the line below.
sudo touch ~/.R/Makevars && sudo echo 'CPPFLAGS="-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"' >> ~/.R/Makevars

3) remove rstan and StanHeaders package from R. 

4) install StanHeaders(2.18 version) 

5) install rstan(2.19 version)

Tada, my rstan is running again!

**Comment by cring-toxstrategies** [comment]
As of September 18 2019, I had this problem on Mac OS Mojave 10.14.6, after updating R following instructions at [https://cran.r-project.org](https://cran.r-project.org): installing clang 8.0.0 and gfortran 6.1, then installing R 3.6.1, then installing StanHeaders version 2.19 and rstan version 2.19.2 (both from CRAN).

I solved it by installing Xcode Command Line Tools by typing at the Terminal command prompt

`xcode-select --install`

then start R. 

Then at the R command line,

`remove.packages("rstan")`
`remove.packages("StanHeaders")`
`if (file.exists(".RData")) file.remove(".RData")`

Restart R, then

`install.packages("StanHeaders")`
`install.packages("rstan")`

Then I was able to compile and run my Stan model no problem.

I did not have to edit the Makevars file (which is a good thing, since I could not find it).

**Comment by lukeholman** [comment]
I got here by Googling the error message. cring's solution in the previous message solved it for me, i.e. delete and re-install those two packages. Thanks!

**Comment by l-psych** [comment]
Hi, 

Sorry for responding to a closed topic, but I am experiencing the same issues as above and have tried the solutions above as far as I could. I am familiar with R and using lmer, glmer models etc., but I am new to using rstan. I have tried to follow cring's advice as I also could not find the R makevars file, but couldn't run this line in Xcode: xcode-select --install
I am not familiar with Xcode, so not sure if I am doing something wrong here. 

When I try to run this brm model (or any other version of this for that matter)
> try_mod <- brm(slidervalue_p ~ o_group + (1|f_ppn), data = data_perc2, family = 'Beta', prior = set_prior('Beta(1/3, 1/3)'), warmup = 1000, iter = 4000, chains = 4)

I get the following error message:
Compiling the C++ model
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from filed2149926571.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/in
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB filed2149926571.cpp 2> filed2149926571.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

I have just upgraded to macOS Catalina (10.15)
Xcode version 11.1
R version 3.6
rstan version 2.19.2

Any suggestions would be very much appreciated!

**Comment by bgoodri** [comment]
RStan basically does not work on Catalina yet.
