### ISSUE TITLE
Cannot fit the schools.stan model

### ISSUE THREAD

**Issue by pcsksa5** [stan-dev/rstan#785]
#### Summary:
Even though rstan used to run without issues (for my simple models), I started having problems with even the simplest of them. I installed, deleted and reinstalled R, Rstudion, and Rtools. The problem remains. I cannot even model the simple schools.stan example model.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
I follow the rstan installation instructions and have no issue or errors. However, when I run the fit model as described in the installation example, I get the following message:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! g++.exe: error: Files/R/R-3.6.3/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: file3a05dba4079.o] Error 1
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.3/bin/x64/R CMD SHLIB file3a05dba4079.cpp 2> file3a05dba4079.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

#### Current Output:
NA

#### Expected Output:
NA

#### RStan Version:
The version of RStan is: ‘2.19.3’

#### R Version:
The version of R is: "R version 3.6.3 (2020-02-29)"

#### Operating System:
Windows 10

**Comment by andrjohns** [comment]
This is a known issue with StanHeaders 2.21 unfortunately. A workaround is to call ```stan``` without loading RStan first. So rather than calling:
```
library(rstan)
stan(model, data)
```

Use:
```
rstan::stan(model, data)
```

**Comment by pcsksa5** [comment]
Hello Andrew, and thank you for your reply. Unfortunately, I still get issues:

 > library("rstan") 
Loading required package: StanHeaders
Loading required package: ggplot2
rstan (Version 2.21.1, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
For improved execution time, we recommend calling
Sys.setenv(LOCAL_CPPFLAGS = '-march=native -mtune=native')
> options(mc.cores = parallel::detectCores())
> rstan_options(auto_write = TRUE)
> schools_dat <- list(J = 8, 
+                     y = c(28,  8, -3,  7, -1,  1, 18, 12),
+                     sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
> fit <- rstan::stan(file = 'schools.stan', data = schools_dat)
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\petros\AppData\Local\Temp\RtmpCQvwAd\file372c4ee910aa.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file372c6f191c2.cpp 2> file372c6f191c2.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file372c6f191c2.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

**Comment by lauswullum** [comment]
**UPDATE** 

Using `rstan::([...])` worked. I just needed to manually close and reopen Rstudio, instead of just restarting *r-session* from within Rstudio.

Thanks

------------
Hi, I get the exact same error when running the 8 schools example, and have not been able to fix it.

**My Issue:**
When calling 
```{r}
library(tidyverse)
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))

rstan::stan(file = "schools.stan", data = schools_dat)
```
or
```{r}
library(tidyverse)
library(rstan)
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit = stan(file = "schools.stan", data = schools_dat)
```
Either way, I get:

> \>rstan::stan(file = "schools.stan", data = schools_dat)
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file39fc71d27bf2.cpp 2> file39fc71d27bf2.cpp.err.txt' had status 1
2: In file(con, "r") :
  cannot open file 'file39fc71d27bf2.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

**Comment by FredFeinberg** [comment]
This may not be THE problem, but the stan file is called 8schools.stan, but the command as listed is stan(file = 'schools.stan', data = schools_dat); it should be stan(file = '8schools.stan', data = schools_dat).

I cannot get it to work either, but for completely different reasons.

**Comment by stat-cz** [comment]
Has someone solved this problem? I have the same question
```
> rstan:::rstudio_stanc("C:/Users/lpb/Desktop/8schools.stan")
C:/Users/...../8schools.stan is syntactically correct.
> ##############################
> ## 8 schools example
> ##############################
> setwd("C:/Users/...")
> library(rstan)
Loading required package: StanHeaders
Loading required package: ggplot2
**rstan (Version 2.21.1, GitRev: 2e1f913d3ca3)**
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
For improved execution time, we recommend calling
Sys.setenv(LOCAL_CPPFLAGS = '-march=native -mtune=native')
> library(bayesplot)
**This is bayesplot version 1.7.2**
- Online documentation and vignettes at mc-stan.org/bayesplot
- bayesplot theme set to bayesplot::theme_default()
   * Does _not_ affect other ggplot2 plots
   * See ?bayesplot_theme_set for details on theme setting
> schools_dat <- list(J = 8, 
+                     y = c(28,  8, -3,  7, -1,  1, 18, 12),
+                     sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
> fit_8schools <- stan(file = '8schools.stan', data = schools_dat)
_The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
**Error in file(con, "r") : cannot open the connection**
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\....\file259447e46fd0.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'D:/ProgramFiles/......./R CMD SHLIB file2594752a1436.cpp 2> file2594752a1436.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file2594752a1436.cpp.err.txt': No such file or directory
**Error in sink(type = "output") : invalid connection**_
```

**Comment by lauswullum** [comment]
Hi @stat-cz , The solution is to NOT write `library(rstan)` but call
```
fit_8schools <- rstan::stan(file = '8schools.stan', data = schools_dat)
```
without loading rstan library first.

However, you probably have to close and reopen Rstudio, and delete the line `library(rstan)`
It is apperently not sufficient to restart the *R-session*. I needed to close and reopen Rstudio.

Hope this helps

**Comment by pcsksa5** [comment]
Thank you for the suggestion. Unfortunately, even without calling the library, I get the same issues. It is a shame because such issues prevent new interest and research to develop.
> fit_8schools <- rstan::stan(file = '8schools.stan', data = schools_dat)
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file128c3ea61417.o:file128c3ea61417.cpp:(.text+0x14ec): undefined reference to `rstan::stan_fit::stan_fit(SEXPREC*, int)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file128c3ea61417.o:file128c3ea61417.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D1Ev[_ZN3tbb8internal26task_scheduler_observer_v3D1Ev]+0x14): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file128c3ea61417.o:file128c3ea61417.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1c): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/
In addition: Warning message:
In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\petros\AppData\Local\Temp\Rtmp4KtGfQ\file128c1c3337b8.stan', reason 'No such file or directory'
Error in sink(type = "output") : invalid connection

**Comment by 942kid** [comment]
@pcsksa5, I have the same errors under Windows 10:

Source:

```r
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit <- rstan::stan(file = 'schools.stan', data = schools_dat)
```

Routput:

```
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file1d1414c162f7.o:file1d1414c162f7.cpp:(.text+0x15fc): undefined reference to `rstan::stan_fit::stan_fit(SEXPREC*, int)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file1d1414c162f7.o:file1d1414c162f7.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D1Ev[_ZN3tbb8internal26task_scheduler_observer_v3D1Ev]+0x14): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file1d1414c162f7.o:file1d1414c162f7.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1c): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/
In addition: Warning message:
In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\fwu1\AppData\Local\Temp\RtmpmGkA7y\file1d14508d6dfe.stan', reason 'No such file or directory'
Error in sink(type = "output") : invalid connection
```

`sessionInfo()`: 

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5           compiler_4.0.2       pillar_1.4.6         prettyunits_1.1.1    tools_4.0.2         
 [6] pkgbuild_1.1.0       jsonlite_1.7.0       lifecycle_0.2.0      tibble_3.0.3         gtable_0.3.0        
[11] pkgconfig_2.0.3      rlang_0.4.7          cli_2.0.2            rstudioapi_0.11      parallel_4.0.2      
[16] curl_4.3             loo_2.3.1            gridExtra_2.3        withr_2.2.0          dplyr_1.0.0         
[21] generics_0.0.2       vctrs_0.3.2          tidyselect_1.1.0     stats4_4.0.2         grid_4.0.2          
[26] glue_1.4.1           inline_0.3.15        R6_2.4.1             processx_3.4.3       fansi_0.4.1         
[31] rstan_2.21.1         purrr_0.3.4          ggplot2_3.3.2        callr_3.4.3          magrittr_1.5        
[36] codetools_0.2-16     matrixStats_0.56.0   scales_1.1.1         ps_1.3.3             StanHeaders_2.21.0-5
[41] ellipsis_0.3.1       assertthat_0.2.1     colorspace_1.4-1     V8_3.2.0             RcppParallel_5.0.2  
[46] munsell_0.5.0        crayon_1.3.4        
```

**Comment by jgabry** [comment]
Sorry you're getting errors. If you're running windows can you try the solution in this thread? https://discourse.mc-stan.org/t/rstan-on-windows/16673

**Comment by pcsksa5** [comment]
Unfortunately, even when using the advice in the thread, I get the following:
> fit <- stan(file = '8schools.stan', data = schools_dat)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! g++.exe: error: C:/Program: No such file or directory
g++.exe: error: Files/R/R-4.0.2/library/rstan/lib/x64/libStanServices.a: No such file or directory
In addition: Warning message:
In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\petros\AppData\Local\Temp\RtmpwNIa7p\file4e0403b2adc.stan', reason 'No such file or directory'
Error in sink(type = "output") : invalid connection

**Comment by jgabry** [comment]
Sorry it's still not working. @bgoodri @bbbales2 any ideas on this Windows issue that @pcsksa5 is encountering?

**Comment by bgoodri** [comment]
Yeah, it will be fixed soon.

**Comment by jgabry** [comment]
Just wanted to follow up on this. @pcsksa5 were you ever able to get RStan installed?

**Comment by pcsksa5** [comment]
@jgabry Yes, the installation never showed me an error/issue. In the past, I had also been able to run a few models. However, when I needed to reinstall (again without any errors/issues) and then test "rstan" using the "schools" example, I then keep on having issues.

**Comment by jgabry** [comment]
Do you still get the exact same message as in your comment above (https://github.com/stan-dev/rstan/issues/785#issuecomment-661307071)? If you're getting different error/warning messages can you share them?

**Comment by pcsksa5** [comment]
Hi,

sorry for the late reply, but I tried to start from scratch and reinstalled R-studio, R, rstan.
I get the following:
> library(rstan)
Loading required package: StanHeaders
Loading required package: ggplot2
rstan (Version 2.21.2, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
Do not specify '-march=native' in 'LOCAL_CPPFLAGS' or a Makevars file
> fit <- stan(file = 'schools.stan', data = schools_dat)
Error in withr::set_makevars(new, path, state, assignment = assignment) : 
  Multiple results for CXX14FLAGS found, something is wrong.FALSE
In addition: Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  '-E' not found

**Comment by jgabry** [comment]
Thanks for following up. I thought this should have been fixed by the latest release. @bgoodri and @SteveBronder it looks like there's still the problem that `withr::set_makevars()` errors if duplicate entries found. 

@pcsksa5 I think we can work around this problem and get you up and running. Can you share the contents of your `Makevars.win` and `Makevars` files? Those can be accessed via 

```r
file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win"))
file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars"))
```

**Comment by pcsksa5** [comment]
Hi,
Thank you for your response.
The file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win")):

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=corei7 -mtune=corei7
CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=corei7 -mtune=corei7
CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

Re the file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars")) the result is an empty text file.

**Comment by jgabry** [comment]
Ok I think having all those duplicates in there is the source of this error 

```
Error in withr::set_makevars(new, path, state, assignment = assignment) :
Multiple results for CXX14FLAGS found, something is wrong
```

My hunch is that you can just delete everything from that file and it should work (it at least won't make anything worse). @SteveBronder @bgoodri is that our recommendation now?

**Comment by pcsksa5** [comment]
Could you please provide some more details on what I should try deleting?

**Comment by jgabry** [comment]
I was thinking all of this: 

> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=corei7 -mtune=corei7
> CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=corei7 -mtune=corei7
> CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7
> 
> CXX14FLAGS=-O3 -march=native -mtune=native
> CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

**Comment by jgabry** [comment]
If that gets it working then I recommend you also add the line below (as the only line in the file), which is suggested in @bgoodri's post on the Stan forums https://discourse.mc-stan.org/t/rstan-on-windows/16673. That should make Stan faster. 

```
CXX14FLAGS=-O3 -mtune=native -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 
```

@bgoodri @SteveBronder is that the latest recommendation for makevars flags on windows?

**Comment by SteveBronder** [comment]
I tried out whether multiple flags worked with rstan the other day and I thought it was fixed but can take a look

@pcsksa5 for clarification what @jgabry means is that you want just one `CXX14FLAGS` and `CXX11FLAGS` in your `Makevars.win` We had a bug from trying to get around a bug in Windows mingw (lol) where passing the compiler flag `-march=native` would cause rstan to crash.

>  is that the latest recommendation for makevars flags on windows?

So the `-m*` flags turn on specific instruction sets that Windows `mingw` doesn't detect. It's okay for people to try it but if it doesn't work then just put `CXX14FLAGS=-O3 -mtune=native` in your `Makevars.win`

**Comment by jgabry** [comment]
On Mon, Aug 3, 2020 at 6:46 PM Steve Bronder <notifications@github.com>
wrote:

> I tried out whether multiple flags worked with rstan the other day and I
> thought it was fixed but can take a look
>

Thanks. Maybe it's fixed on GitHub but wasn't fixed before @bgoodri
submitted to CRAN most recently?

**Comment by SteveBronder** [comment]
Weird, I installed the latest version from CRAN (2.21.2) and with my `Makevars` as  

```make
CXX14FLAGS= -Wno-ignored-attributes
CXX14FLAGS= -Wno-ignored-attributes
CXX11FLAGS= -O3 -g0
CXX11FLAGS= -O3 -g0
CXX14=g++
CXX14=g++

```

the below compiled fine

```R
library(rstan)

schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))

foo = stan(model_code = "// saved as schools.stan
data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}", data = schools_dat, cores = 4, verbose = TRUE)

```

**Comment by jgabry** [comment]
Hmm, that's weird indeed.

**Comment by pcsksa5** [comment]
Hello,

You were right. Deleting everything from the file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win")) made it work. At the end it gave the following message:
Warning messages:
1: In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  '-E' not found
2: There were 6 divergent transitions after warmup. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
to find out why this is a problem and how to eliminate them. 
3: Examine the pairs() plot to diagnose sampling problems

Entering in the same file the: CXX14FLAGS=-O3 -mtune=native -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 
made it work faster and showing:
Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  '-E' not found

Thank you.

**Comment by jgabry** [comment]
I'm not sure why there's that warning message 

```
Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
'-E' not found
```

but I'm glad it working! If it's running ok then you can just ignore that warning I think.

**Comment by JakobFjellstrom** [comment]
Hi everyone! I've been having some issues with stan for the past few days, and when I thought the problem was solved, I now have this error instead:
Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  '-E' not found
Kinda cryptic, and I don't know how to solve it. Any help would be appriciated!

**Comment by bgoodri** [comment]
That's not an error. Don't worry about it.
