### ISSUE TITLE
StanHeaders changes compiler flags in new version

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [stan-dev/rstan#786]
#### Summary:
When loading the StanHeader library it changes the compiler flags and this causes errors when compiling TMB models. 

#### Description:
The package `tmbstan` links the package `TMB` to Stan via `rstan`. After a recent upgrade of packages I was unable to compile TMB models after loading `tmbstan`. This is because when StanHeaders is loaded, it changes the compiler flags, adding

````
-include C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/Users/cole.monnahan/RLibs/StanHeaders/include" -I "C:/Users/cole.monnahan/RLibs/RcppEigen/include"
````
when using `TMB::compile`.

These additional flags pointing to StanHeaders causes an error in compilation and a restart of R is required to compile.

#### Reproducible Steps:

````
install.packages('tmbstan')
install.packages('TMB')
````

Then run the following steps for version 2.19.0 and 2.21.0.5 of StanHeaders.

````
library(TMB)
runExample('simple', clean=TRUE)
````

to get correct behavior, and then **restart R** and run

````
library(TMB)
library(StanHeaders)
runExample('simple', clean=TRUE)
````

Do this for version StanHeaders 2.19.0 and you will see that it works fine, but fails for 2.21.0.5.

#### Current Output:
After loading `StanHeaders` and trying to compile a model, this is the compiler configuration output to the console.

````
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple          -O3 -Wno-unused-variable -Wno-unused-function -c simple.cpp -o simple.o
C:/Rtools/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o simple.dll tmp.def simple.o -LC:/PROGRA~1/R/R-36~1.3/bin/x64 -lR
````

After upgrading to `StanHeaders` to version 2.21.0.5 the same command is:

````
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple        -include C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/Users/cole.monnahan/RLibs/StanHeaders/include" -I "C:/Users/cole.monnahan/RLibs/RcppEigen/include"   -O3 -Wno-unused-variable -Wno-unused-function -c simple.cpp -o simple.o
````

#### Expected Output:
Loading StanHeaders should not affect the compiler flags for TMB, as was the behavior in previous versions of StanHeaders.

#### RStan Version:
2.19.3

#### R Version:
3.6.3

#### Operating System:
Windows 10

**Comment by jgabry** [comment]
Thanks for reporting this. @bgoodri is it intentional/necessary for StanHeaders to do this?

**Comment by bgoodri** [comment]
Yeah, recent versions of Stan Math are backward incompatible due to
requiring Eigen.hpp be included first but then moving the file. What is the
error message? I'll see what I can do about it.

**Comment by bgoodri** [comment]
The issue seems to be that now both StanHeaders and TMB are defining an
Eigen plugin. I don't know how that is supposed to work, but I don't get
any errors with rstan 2.21.1 which I would like to upload to CRAN.

**Comment by SteveBronder** [comment]
The tmb would have to include the stan math plugin within their eigin plugin. Is this a tmb extension or is stan math a normal dependency in tmb?

**Comment by Cole-Monnahan-NOAA** [comment]
I'm tagging @kaskr the author of TMB to see if he will comment on the Eigen plugin issue. 

TMB does not depend on Stan math, nor anything in Stan. tmbstan links the gradients/log-posteriors calculated by TMB into the Stan samplers via rstan. 

https://github.com/kaskr/adcomp/TMB
https://github.com/kaskr/tmbstan

**Comment by kaskr** [comment]
Here's a simpler TMB independent example.
It seems my build system is broken after loading `StanHeaders  2.21.0-5`:

```r
system("touch foo.cpp; R CMD SHLIB foo.cpp") ## Compiles
library(StanHeaders)
system("touch foo.cpp; R CMD SHLIB foo.cpp") ## Doesn't compile
```

Difference in compiler flags before/after is:

```
-include /zhome/8a/0/39821/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I '/zhome/8a/0/39821/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include'
```

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.7 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /zdata/groups/nfsopt/intel/2017update4/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=iso_8859_1 LC_NUMERIC=C        LC_TIME=C          
 [4] LC_COLLATE=C        LC_MONETARY=C       LC_MESSAGES=C      
 [7] LC_PAPER=C          LC_NAME=C           LC_ADDRESS=C       
[10] LC_TELEPHONE=C      LC_MEASUREMENT=C    LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] StanHeaders_2.21.0-5

loaded via a namespace (and not attached):
[1] compiler_3.6.2     RcppParallel_5.0.2
```

**Comment by SteveBronder** [comment]
The Eigen plugin stuff for stan happens [here](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/Eigen.hpp#L1).  @andrjohns do you think we could do something like

1. Check if `EIGEN_MATRIXBASE_PLUGIN` is already defined.
2. If so, make a temp macro `STAN_TEMP_EIGEN_MATRIXBASE_PLUGIN`
3. In our plugins, include `STAN_TEMP_EIGEN_MATRIXBASE_PLUGIN` if it's defined

Then I think this would let other people have their own eigen plugins

**Comment by andrjohns** [comment]
Can you clarify step 3? Given that ```#define EIGEN_MATRIXBASE_PLUGIN``` can only be called once, both the Stan and TMB eigen plugins need to get included in the same call. Did the temp macro work around that? (if so, neat!). I believe the simple workaround is to have other packages ```#include <stan/math/prim/eigen_plugins.h>``` in their plugin before they define the macro.

Do we know if TMB has only recently introduced their plugin, or if it's been present for a while and is now breaking? It might be that changing the StanHeaders compilation flag has caused Stan's plugin to be loaded first and then the Eigen headers get loaded which lock in any changes to ```EIGEN_MATRIXBASE_PLUGIN```, and stop TMB's from getting included.

@Cole-Monnahan-NOAA or @kaskr  can you post the compiler errors that you're getting? That will help us narrow down what's going on

**Comment by andrjohns** [comment]
Actually, I believe the issue is that the compilation arguments above use ```-std=gnu++11```, and it needs ```-std=gnu++14``` or ```-std=c++1y```

If run the code @kaskr posted above without requesting the higher standard, I get compilation errors:
```
system("touch foo.cpp; R CMD SHLIB foo.cpp") ## Doesn't compile
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG      -include /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I '/home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include' -I '/home/andrew/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include' -fpic  -O3 -march=native -mtune=native -Wno-attributes -Wno-ignored-attributes -Wno-deprecated-declarations -c foo.cpp -o foo.o
In file included from /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/MatrixBase.h:130,
                 from /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:436,
                 from /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
                 from /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from <command-line>:
/home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/eigen_plugins.h:22:30: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
   22 | using double_return_t = std::conditional_t<std::is_const<std::remove_reference_t<T>>::value,
      |                              ^~~~~~~~~~~~~
      |                              conditional
```
Where the issue is that ```conditional_t``` wasn't introduced till c++14. If I recompile with the ```std=c++1y``` flag, it all works fine:
```
> system("touch foo.cpp; R CMD SHLIB foo.cpp") ## Doesn't compile
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG      -include /home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I '/home/andrew/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include' -I '/home/andrew/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include' -fpic  -O3 -std=c++1y  -march=native -mtune=native -Wno-attributes -Wno-ignored-attributes -Wno-deprecated-declarations -c foo.cpp -o foo.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o foo.so foo.o -L/usr/lib/R/lib -lR
```

**Comment by andrjohns** [comment]
Basically, because loading StanHeaders includes ```stan/math/prim/mat/fun/Eigen.hpp``` in every compilation, it's inadvertently requiring c++14 for any compilation that happens after loading

**Comment by Cole-Monnahan-NOAA** [comment]
I get similar errors, see this issue: https://github.com/kaskr/tmbstan/issues/16

**Comment by andrjohns** [comment]
As a workaround for now, you can add ```CXXFLAGS += -std=c++1y``` to your Makevars file

**Comment by bgoodri** [comment]
Is TMBstan not requiring C++14? I thought we fixed that twice

https://github.com/kaskr/tmbstan/issues/13

**Comment by andrjohns** [comment]
I actually still get errors with TMB after adding the c++1y flag:
```
> library(tmbstan)
> runExample('simple', clean=TRUE)
Cleanup:
Building example simple 
Note: Using Makevars in C:/Users/Andrew Johnson/Documents/.R/Makevars 
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -IC:/R/WIN-LI~1/4.0/TMB/include -IC:/R/WIN-LI~1/4.0/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple        -include C:/R/win-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/R/win-library/4.0/StanHeaders/include" -I "C:/R/win-library/4.0/RcppEigen/include"   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -O3 -std=c++1y -march=native -mtune=native -Wno-deprecated-declarations -Wno-unused-function -Wno-ignored-attributes -Wno-parentheses -Wno-sign-compare -Wno-attributes -Wno-int-in-bool-context -Wno-unused-local-typedefs -Wno-unused-but-set-variable -c simple.cpp -o simple.o
In file included from C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/pbeta.hpp:98,
                 from C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/atomic.hpp:21,
                 from C:/R/WIN-LI~1/4.0/TMB/include/TMB.hpp:96,
                 from simple.cpp:2:
C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/toms708.cpp: In function 'void atomic::toms708::bratio(Float, Float, Float, Float, Float*, Float*, int*, int)':
C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/toms708.cpp:40:33: error: 'M_LN2' was not declared in this scope
 #define R_Log1_Exp(x)   ((x) > -M_LN2 ? log(-rexpm1(x)) : log1p(-exp(x)))
                                 ^~~~~
```
But these seem unrelated to RStan/StanHeaders

**Comment by andrjohns** [comment]
There are the same errors with 'pure' TMB, which suggests that TMB doesn't play well with c++14 for some reason:
```
> library(TMB)
Building example simple 
Note: Using Makevars in C:/Users/Andrew Johnson/Documents/.R/Makevars 
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -IC:/R/WIN-LI~1/4.0/TMB/include -IC:/R/WIN-LI~1/4.0/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple          -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -O3 -std=c++1y -march=native -mtune=native -Wno-deprecated-declarations -Wno-unused-function -Wno-ignored-attributes -Wno-parentheses -Wno-sign-compare -Wno-attributes -Wno-int-in-bool-context -Wno-unused-local-typedefs -Wno-unused-but-set-variable -c simple.cpp -o simple.o
In file included from C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/pbeta.hpp:98,
                 from C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/atomic.hpp:21,
                 from C:/R/WIN-LI~1/4.0/TMB/include/TMB.hpp:96,
                 from simple.cpp:2:
C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/toms708.cpp: In function 'void atomic::toms708::bratio(Float, Float, Float, Float, Float*, Float*, int*, int)':
C:/R/WIN-LI~1/4.0/TMB/include/tiny_ad/beta/toms708.cpp:40:33: error: 'M_LN2' was not declared in this scope
 #define R_Log1_Exp(x)   ((x) > -M_LN2 ? log(-rexpm1(x)) : log1p(-exp(x)))
                                 ^~~~~
```

**Comment by SteveBronder** [comment]
idt that's a C++14 issue is it? It looks like they have a macro `M_LN2` that's not being picked up for some reason?

**Comment by andrjohns** [comment]
Yep, but there's no error without the ```std=c++1y``` flag
________________________________

**Comment by DanOvando** [comment]
Not exactly an ideal permanent solution but  calling `Sys.unsetenv("PKG_CXXFLAGS")` after loading libraries seems to solve that problem for me (solution from @bgoodri  to similar sourceCpp problem [here](https://discourse.mc-stan.org/t/dealing-with-catalina-ii/11802/145?u=danovando)). Restarting R, commenting out `Sys.unsetenv("PKG_CXXFLAGS")` and rerunning produces same error as reported by @Cole-Monnahan-NOAA 
``` r
library(TMB)
library(StanHeaders)
Sys.unsetenv("PKG_CXXFLAGS")

runExample('simple', clean=TRUE)
#> Cleanup:
#> Building example simple 
#> Note: Using Makevars in /Users/danovan/.R/Makevars 
#> Build time 24.518 seconds
#> 
#> Running example simple 
#> 
#> > require(TMB)
#> 
#> > dyn.load(dynlib("simple"))
#> 
#> > ## Test data
#> > set.seed(123)
#> 
#> > y <- rep(1900:2010,each=2)
#> 
#> > year <- factor(y)
#> 
#> > quarter <- factor(rep(1:4,length.out=length(year)))
#> 
#> > period <- factor((y > mean(y))+1)
#> 
#> > ## Random year+quarter effect, fixed period effect:
#> > B <- model.matrix(~year+quarter-1)
#> 
#> > A <- model.matrix(~period-1)
#> 
#> > B <- as(B,"dgTMatrix")
#> 
#> > A <- as(A,"dgTMatrix")
#> 
#> > u <- rnorm(ncol(B)) ## logsdu=0
#> 
#> > beta <- rnorm(ncol(A))*100
#> 
#> > eps <- rnorm(nrow(B),sd=1) ## logsd0=0
#> 
#> > x <- as.numeric( A %*% beta + B %*% u + eps )
#> 
#> > ## Fit model
#> > obj <- MakeADFun(data=list(x=x, B=B, A=A),
#> +                  parameters=list(u=u*0, beta=beta*0, logsdu=1, logsd0=1),
#> +              .... [TRUNCATED] 
#> 
#> > opt <- nlminb(obj$par, obj$fn, obj$gr)

devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS Catalina 10.15.5      
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Los_Angeles         
#>  date     2020-07-10                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version  date       lib source        
#>  assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
#>  backports      1.1.8    2020-06-17 [1] CRAN (R 4.0.0)
#>  callr          3.4.3    2020-03-28 [1] CRAN (R 4.0.0)
#>  cli            2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
#>  desc           1.2.0    2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools       2.3.0    2020-04-10 [1] CRAN (R 4.0.0)
#>  digest         0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
#>  ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
#>  fs             1.4.2    2020-06-30 [1] CRAN (R 4.0.0)
#>  glue           1.4.1    2020-05-13 [1] CRAN (R 4.0.0)
#>  highr          0.8      2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools      0.5.0    2020-06-16 [1] CRAN (R 4.0.0)
#>  knitr          1.29     2020-06-23 [1] CRAN (R 4.0.0)
#>  lattice        0.20-41  2020-04-02 [1] CRAN (R 4.0.2)
#>  magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.0)
#>  Matrix         1.2-18   2019-11-27 [1] CRAN (R 4.0.2)
#>  memoise        1.1.0    2017-04-21 [1] CRAN (R 4.0.0)
#>  pkgbuild       1.0.8    2020-05-07 [1] CRAN (R 4.0.0)
#>  pkgload        1.1.0    2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
#>  processx       3.4.3    2020-07-05 [1] CRAN (R 4.0.0)
#>  ps             1.3.3    2020-05-08 [1] CRAN (R 4.0.0)
#>  R6             2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
#>  RcppParallel   5.0.2    2020-06-24 [1] CRAN (R 4.0.0)
#>  remotes        2.1.1    2020-02-15 [1] CRAN (R 4.0.0)
#>  rlang          0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
#>  rmarkdown      2.3      2020-06-18 [1] CRAN (R 4.0.0)
#>  rprojroot      1.3-2    2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
#>  StanHeaders  * 2.21.0-5 2020-06-09 [1] CRAN (R 4.0.0)
#>  stringi        1.4.6    2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr        1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat       2.3.2    2020-03-02 [1] CRAN (R 4.0.0)
#>  TMB          * 1.7.16   2020-01-15 [1] CRAN (R 4.0.0)
#>  usethis        1.6.1    2020-04-29 [1] CRAN (R 4.0.0)
#>  withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun           0.15     2020-06-21 [1] CRAN (R 4.0.0)
#>  yaml           2.2.1    2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bgoodri** [comment]
I think I can take the setting of PKG_CXXFLAGS out of StanHeaders now that
the equivalent thing is being done in rstan.

**Comment by jgabry** [comment]
Has this been resolved? If so, we should close this (there are way too many open RStan issues that are actually resolved). If not, is there something else we can do to solve this?

**Comment by bgoodri** [comment]
I think it is fixed by StanHeaders 2.21.0-6 .

**Comment by Cole-Monnahan-NOAA** [comment]
I tested this and can confirm that installing StanHeaders 2.21.0-6 from CRAN fixes this issue. Thank you for fixing it.

**Comment by jgabry** [comment]
Ok great, thanks for confirming!
